
software_list = [
    # (Name, Category, Description, Ubuntu_Method, Windows_Method)
    ("7-Zip", "Utilities", "File archiver", "✅ bin", "✅ winget"),
    ("Adobe Acrobat Reader", "Productivity", "PDF viewer", "—", "✅ winget"),
    ("Android Studio", "Dev Tools", "IDE for Android", "—", "✅ winget"),
    ("AngryIP Scanner", "Network", "IP address scanner", "—", "✅ winget"),
    ("Ansible", "Dev Tools", "Config management", "✅ pipx", "—"),
    ("Ant", "Dev Tools", "Java build tool", "✅ sdkman", "✅ scoop"),
    ("Antigravity", "Dev Tools", "Auto-updater", "✅ apt", "—"),
    ("AnyDesk", "Utilities", "Remote desktop", "—", "✅ winget"),
    ("Apache (httpd)", "Web Server", "HTTP server", "✅ apt", "—"),
    ("Apache Directory Studio", "Database", "LDAP browser", "✅ flatpak", "—"),
    ("Apache OpenOffice", "Productivity", "Office suite", "—", "✅ winget"),
    ("Arduino IDE", "Dev Tools", "IDE for Arduino", "—", "✅ winget"),
    ("Aria2", "Utilities", "CLI downloader", "✅ apt", "—"),
    ("AutoHotkey", "Utilities", "Automation scripting", "—", "✅ winget"),
    ("Azure CLI", "Cloud", "Azure management", "✅ apt", "—"),
    ("Azure Data Studio", "Database", "DB editor", "—", "✅ winget"),
    ("Bitvise SSH Client", "Network", "SSH client", "—", "✅ winget"),
    ("Bitwarden", "Security", "Password manager", "✅ flatpak", "✅ winget"),
    ("BlueJ", "Dev Tools", "Java IDE", "✅ deb", "✅ winget"),
    ("Bottles", "Virtualisation", "Wine manager", "✅ flatpak", "—"),
    ("btop", "Utilities", "System monitor", "✅ apt", "—"),
    ("Build Essentials", "Dev Tools", "C/C++ build tools", "✅ apt", "—"),
    ("BulkCrapUninstaller", "Utilities", "Uninstaller", "—", "✅ winget"),
    ("Bun", "Dev Tools", "JS runtime", "✅ script", "✅ winget"),
    ("Burp Suite Community", "Security", "Web proxy", "—", "✅ winget"),
    ("Calibre", "Productivity", "E-book manager", "—", "✅ winget"),
    ("CCleaner", "Utilities", "System cleaner", "—", "✅ winget"),
    ("ChromeDriver", "Dev Tools", "Selenium driver", "—", "✅ winget"),
    ("Cider (Apple Music)", "Multimedia", "Apple Music client", "✅ apt", "—"),
    ("Cisco Packet Tracer", "Network", "Network sim", "✅ deb", "—"),
    ("Cloudflared", "Network", "Cloudflare tunnel", "✅ apt", "✅ winget"),
    ("Conky", "Utilities", "System monitor", "✅ apt", "—"),
    ("CrystalDiskInfo", "Utilities", "HDD/SSD monitor", "—", "✅ winget"),
    ("curl", "Dev Tools", "CLI data transfer", "—", "✅ winget"),
    ("DBeaver Community", "Database", "Universal DB tool", "✅ apt", "✅ winget"),
    ("DeadBeeF", "Multimedia", "Audio player", "✅ deb", "—"),
    ("Discord", "Communication", "Chat & VoIP", "✅ flatpak", "✅ winget"),
    ("draw.io", "Productivity", "Diagramming tool", "✅ deb", "✅ winget"),
    ("Easy Effects", "Multimedia", "Audio processor", "✅ apt", "—"),
    ("Eclipse JEE", "Dev Tools", "Java IDE", "—", "✅ scoop"),
    ("EdgeDriver", "Dev Tools", "Selenium driver", "—", "✅ winget"),
    ("Ente Auth", "Security", "2FA manager", "✅ flatpak", "✅ winget"),
    ("FastCopy", "Utilities", "Fast file copy", "—", "✅ winget"),
    ("FastFetch", "Utilities", "System info", "—", "✅ winget"),
    ("FFMPEG", "Multimedia", "Video processor", "✅ apt", "✅ winget"),
    ("FileConverter", "Utilities", "File converter", "—", "✅ winget"),
    ("Firefox", "Browser", "Web browser", "✅ apt/ppa", "✅ winget"),
    ("Flutter", "Dev Tools", "UI toolkit", "—", "✅ scoop"),
    ("foobar2000", "Multimedia", "Audio player", "—", "✅ winget"),
    ("GeckoDriver", "Dev Tools", "Selenium driver", "—", "✅ winget"),
    ("GIMP", "Multimedia", "Image editor", "✅ apt", "—"),
    ("Git", "Dev Tools", "Version control", "✅ apt", "✅ winget"),
    ("GitLab Runner", "Dev Tools", "CI/CD runner", "—", "✅ winget"),
    ("GNS3", "Network", "Network sim", "✅ ppa", "—"),
    ("Golang", "Dev Tools", "Go language", "✅ ppa", "✅ winget"),
    ("Google Chrome", "Browser", "Web browser", "✅ apt", "✅ winget"),
    ("Gradle", "Dev Tools", "Build tool", "✅ sdkman", "✅ scoop"),
    ("Groovy", "Dev Tools", "Scripting lang", "✅ sdkman", "✅ scoop"),
    ("Helidon", "Dev Tools", "Microservices", "✅ sdkman", "—"),
    ("htop", "Utilities", "System monitor", "✅ apt", "—"),
    ("HWiNFO", "Utilities", "Hardware info", "—", "✅ winget"),
    ("HxD", "Utilities", "Hex editor", "—", "✅ winget"),
    ("ImgBurn", "Utilities", "Disc burner", "—", "✅ winget"),
    ("Inkscape", "Multimedia", "Vector editor", "✅ apt", "—"),
    ("Insomnia", "Dev Tools", "API client", "✅ deb", "✅ winget"),
    ("IntelliJ IDEA Community", "Dev Tools", "Java IDE", "—", "✅ winget"),
    ("Java (Liberica JDK)", "Dev Tools", "Java runtime", "—", "✅ winget"),
    ("Java (Temurin JDK)", "Dev Tools", "Java runtime", "✅ sdkman", "—"),
    ("JMC", "Dev Tools", "Mission Control", "✅ sdkman", "—"),
    ("JMeter", "Dev Tools", "Load testing", "✅ sdkman", "—"),
    ("Joplin", "Productivity", "Note-taking", "✅ script", "—"),
    ("JReleaser", "Dev Tools", "Release manager", "✅ sdkman", "—"),
    ("KeyStore Explorer", "Security", "Key/cert tool", "✅ deb", "✅ winget"),
    ("Kotlin", "Dev Tools", "Programming lang", "✅ sdkman", "✅ scoop"),
    ("kubectl", "Cloud", "Kubernetes CLI", "✅ apt", "✅ winget"),
    ("KVM / Libvirt / Virt-Manager", "Virtualisation", "Virtualization", "✅ apt", "—"),
    ("Liberica NIK", "Dev Tools", "Native images", "—", "✅ winget"),
    ("LibreOffice", "Productivity", "Office suite", "✅ apt", "✅ winget"),
    ("LibreWolf", "Browser", "Privacy browser", "✅ extrepo", "✅ winget"),
    ("Lua", "Dev Tools", "Scripting lang", "✅ apt", "✅ winget"),
    ("MariaDB Client/Server", "Database", "SQL database", "✅ apt", "✅ winget"),
    ("Maven", "Dev Tools", "Java build tool", "✅ sdkman", "✅ scoop"),
    ("MediaInfo", "Multimedia", "Media info", "—", "✅ winget"),
    ("Meld", "Dev Tools", "Diff tool", "✅ apt", "—"),
    ("Micronaut", "Dev Tools", "Microservices", "✅ sdkman", "✅ scoop"),
    ("Microsoft Edge", "Browser", "Web browser", "✅ apt", "✅ winget"),
    ("Microsoft OneDrive", "Productivity", "Cloud storage", "—", "✅ winget"),
    ("Microsoft Teams", "Communication", "Chat & VoIP", "✅ apt", "✅ winget"),
    ("MongoDB Compass + Shell", "Database", "NoSQL editor", "—", "✅ winget"),
    ("MSSQL Tools", "Database", "SQL Server tools", "✅ apt", "✅ winget"),
    ("MSYS2", "Dev Tools", "POSIX layer", "—", "✅ winget"),
    ("MySQL Client & Shell", "Database", "SQL database", "✅ apt", "✅ winget"),
    ("MySQL Workbench", "Database", "SQL editor", "✅ apt/deb", "✅ winget"),
    ("Nala", "Utilities", "APT frontend", "✅ apt", "—"),
    ("Neovim", "Dev Tools", "Text editor", "✅ ppa", "—"),
    ("NetBeans", "Dev Tools", "Java IDE", "—", "✅ scoop"),
    ("Net-tools", "Network", "Network utils", "✅ apt", "—"),
    ("Nginx", "Web Server", "HTTP server", "✅ apt", "✅ winget"),
    ("Ngrok", "Network", "Tunneling", "✅ apt", "✅ winget"),
    ("Nmap", "Network", "Security scanner", "✅ apt", "✅ winget"),
    ("Node.js", "Dev Tools", "JS runtime", "—", "✅ winget"),
    ("Nomad", "Cloud", "Orchestrator", "—", "✅ winget"),
    ("Notepad++", "Dev Tools", "Text editor", "—", "✅ winget"),
    ("Npcap", "Network", "Packet capture", "—", "✅ winget"),
    ("OBS Studio", "Multimedia", "Streaming/Rec", "✅ ppa", "✅ winget"),
    ("Oh My Posh", "Utilities", "Prompt engine", "✅ script", "✅ winget"),
    ("Ollama", "AI", "LLM runner", "—", "✅ winget"),
    ("OpenTofu", "Cloud", "Infrastructure", "✅ script", "—"),
    ("OpenWebStart", "Dev Tools", "JNLP runner", "—", "✅ winget"),
    ("Oracle Instant Client", "Database", "Database driver", "✅ tar.gz", "✅ scoop"),
    ("Packer", "Cloud", "Image builder", "✅ apt", "✅ winget"),
    ("Paint.NET", "Multimedia", "Image editor", "—", "✅ winget"),
    ("PDFArranger", "Productivity", "PDF tool", "—", "✅ winget"),
    ("Perl", "Dev Tools", "Programming lang", "—", "✅ winget"),
    ("pgAdmin 4", "Database", "Postgres tool", "✅ apt", "✅ winget"),
    ("Pidgin", "Communication", "Multi-protocol IM", "✅ apt", "—"),
    ("Podman", "Virtualisation", "Container engine", "✅ apt", "✅ winget"),
    ("PostgreSQL Client", "Database", "SQL database", "✅ apt", "✅ winget"),
    ("Postman", "Dev Tools", "API platform", "—", "✅ winget"),
    ("PotPlayer", "Multimedia", "Video player", "—", "✅ winget"),
    ("PowerShell", "Utilities", "Shell environment", "—", "✅ winget"),
    ("PowerToys", "Utilities", "Productivity", "—", "✅ winget"),
    ("PuTTY", "Network", "SSH/Telnet", "—", "✅ winget"),
    ("PyCharm Community", "Dev Tools", "Python IDE", "—", "✅ winget"),
    ("Python", "Dev Tools", "Programming lang", "✅ apt", "✅ winget"),
    ("Quarkus", "Dev Tools", "Java framework", "✅ sdkman", "✅ scoop"),
    ("Ruby", "Dev Tools", "Programming lang", "✅ rbenv", "✅ winget"),
    ("Rust", "Dev Tools", "Programming lang", "✅ rustup", "✅ winget"),
    ("sbt", "Dev Tools", "Scala build tool", "✅ sdkman", "✅ scoop"),
    ("Scala", "Dev Tools", "Programming lang", "✅ sdkman", "✅ scoop"),
    ("ShareX", "Utilities", "Screen capture", "—", "✅ winget"),
    ("Spring Boot", "Dev Tools", "Java framework", "✅ sdkman", "✅ scoop"),
    ("SQLcl", "Database", "SQL CLI", "—", "✅ scoop"),
    ("Steam", "Gaming", "Game platform", "—", "✅ winget"),
    ("Surfshark VPN", "Network", "VPN client", "✅ script", "✅ winget"),
    ("Tailscale", "Network", "Mesh VPN", "✅ apt", "✅ winget"),
    ("Telegram", "Communication", "Messaging", "✅ flatpak", "✅ winget"),
    ("Terraform", "Cloud", "Infrastructure", "✅ apt", "✅ winget"),
    ("Thonny", "Dev Tools", "Python IDE", "—", "✅ winget"),
    ("Thunderbird", "Communication", "Email client", "✅ apt", "✅ winget"),
    ("TigerVNC Viewer", "Network", "VNC client", "✅ apt", "—"),
    ("TrafficMonitor", "Utilities", "Network monitor", "—", "✅ winget"),
    ("Transmission", "Utilities", "BitTorrent", "✅ apt", "✅ winget"),
    ("Ungoogled Chromium", "Browser", "Web browser", "✅ ppa", "✅ winget"),
    ("UPX", "Utilities", "Executable packer", "—", "✅ winget"),
    ("USBPcap", "Network", "USB capture", "—", "✅ winget"),
    ("Vagrant", "Cloud", "Env. automation", "✅ apt", "✅ winget"),
    ("VcXsrv", "Network", "X Server", "—", "✅ winget"),
    ("Ventoy", "Utilities", "Bootable USB", "—", "✅ winget"),
    ("Vim", "Dev Tools", "Text editor", "—", "✅ winget"),
    ("VirtualBox", "Virtualisation", "Hypervisor", "✅ apt", "✅ winget"),
    ("Virt-Viewer", "Virtualisation", "VM console", "—", "✅ winget"),
    ("Visual Studio 2022 CE", "Dev Tools", "IDE", "—", "✅ winget"),
    ("VisualVM", "Dev Tools", "JVM monitor", "✅ sdkman", "—"),
    ("Vivaldi", "Browser", "Web browser", "✅ apt", "✅ winget"),
    ("VLC", "Multimedia", "Video player", "✅ apt", "—"),
    ("VMware Workstation", "Virtualisation", "Hypervisor", "✅ bundle/script", "—"),
    ("VNC Viewer", "Network", "VNC client", "—", "✅ winget"),
    ("VS Code", "Dev Tools", "Text editor", "✅ apt", "✅ winget"),
    ("Webex", "Communication", "Video conferencing", "✅ deb", "✅ winget"),
    ("WinDirStat", "Utilities", "Disk usage", "—", "✅ winget"),
    ("WinMerge", "Utilities", "Diff tool", "—", "✅ winget"),
    ("WinSCP", "Network", "SFTP client", "—", "✅ winget"),
    ("WireGuard", "Network", "VPN tunnel", "✅ apt", "✅ winget"),
    ("Wireshark", "Network", "Packet analyzer", "✅ ppa", "✅ winget"),
    ("XnView MP", "Multimedia", "Image viewer", "—", "✅ winget"),
    ("yq", "Dev Tools", "YAML processor", "✅ bin", "—"),
    ("ZapZap (WhatsApp)", "Communication", "WhatsApp client", "✅ flatpak", "—"),
    ("Zoom", "Communication", "Video conferencing", "✅ deb", "✅ winget"),
]

print("| # | Software | Category | Description | Ubuntu | Windows |")
print("|---:|:---|:---|:---|:---|:---|")
for i, (name, cat, desc, ub, win) in enumerate(software_list, 1):
    print(f"| {i} | {name} | {cat} | {desc} | {ub} | {win} |")
